import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";
import { DeviceContextProvider } from "@/hooks/useDevice";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <DeviceContextProvider>
          <body className={inter.className}>{children}</body>
        </DeviceContextProvider>
      </StyledComponentsRegistry>
    </html>
  );
}
